# Generated by Django 4.1.7 on 2023-09-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Жильё', 'verbose_name_plural': 'Жильё'},
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='ad_giver_name',
            new_name='owner_name',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='ad_giver_phone',
            new_name='owner_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='commerce_valid',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='ll',
        ),
        migrations.AddField(
            model_name='flat',
            name='lat',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='flat',
            name='lng',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='flat',
            name='owner_tg',
            field=models.CharField(default=None, max_length=64, verbose_name='Telegram'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Название сите'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='property_type',
            field=models.CharField(choices=[('0', 'Дом'), ('1', '1+1'), ('2', '2+1'), ('3', '3+1'), ('4', '4+1'), ('5', '5+1'), ('6', '6+1+')], default='2+1', max_length=4, verbose_name='Планировка'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='total_floors',
            field=models.PositiveSmallIntegerField(default=12, verbose_name='Всего этажей'),
        ),
    ]
