# Generated by Django 4.1.7 on 2023-09-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residential', '0002_alter_flat_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='owner_name',
            new_name='contact_name',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='owner_phone',
            new_name='contact_phone',
        ),
        migrations.RenameField(
            model_name='flat',
            old_name='owner_tg',
            new_name='contact_tg',
        ),
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Заголовок'),
        ),
    ]
